[package]
name = "community"
version = "0.1.0"
edition = "2021"
authors = ["Emirhan CAMCI <byemir@live.com>"]
description = "High-Speed Harmonic & FFT Core Engine for Power Electronics (AGPLv3)"
license = "AGPL-3.0-or-later"
repository = "https://github.com/yourusername/harmonic-scope-wasm"
keywords = ["fft", "harmonics", "power-electronics", "wasm", "thd"]
categories = ["science", "simulation", "hardware-support"]

[dependencies]
num-complex = "0.4.6"
rustfft = "6.4.1"
